node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse HEAD | cut -c1-10 > .git/commit-id"
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'miteshsjat') {
       def app = docker.build("miteshsjat/docker-excample:${commit_id}", '.').push()
     }
   }
}