node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse HEAD | cut -c1-10 > .git/commit-id"
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install'
     }
   }
   stage('Upload Image to DockerHub') {
            withCredentials([string(credentialsId: 'miteshsjatp', variable: 'dhpass')]) {
               sh "docker build -t miteshsjat/docker-excample:${commit_id} ."
    sh "docker login -u miteshsjat -p ${dhpass} && docker push miteshsjat/docker-excample:${commit_id}"
            }
  }
}
